### ISSUE TITLE
Listed APPLE here https://chiaforkscalculator.com/apple

### ISSUE THREAD

**Issue by daryledesilva** [Apple-Network/apple-blockchain#5]
to the devs:

> Hi, this is the dev for chiaforkscalculator.com. Listed APPLE here: https://chiaforkscalculator.com/
> and the dedicated calculator for APPLE can be found here: https://chiaforkscalculator.com/apple
> 
> please take note that all sections that require a USD value (example: Daily earnings in USD, Price Chart, etc) are all hidden for now. They can be unlocked once there is a confirmation that APPLE will be listed at some point in Chia Fork Traders. If that happens, let me know so that I can enable those sections for you :)
> 
> if you have any questions/comments/suggest feel free to reach out and let me know 😄 thank you!

**Comment by Apple-Network** [comment]
THX
